name: Run Appium Tests   # Workflow name

on:                     # Triggers
  push:
    branches: [ master ]  # Run on push to main
  pull_request:
    branches: [ master ]  # Run on PRs to main

jobs:
  appium-tests:         # Job name
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.16.0'

      - name: Install Appium
        run:
          npm install -g appium
          appium -v
          appium driver install uiautomator2

      - name: Start Appium Server
        run: nohup appium > appium.log 2>&1 &

      - name: Install Maven dependencies
        run: mvn install -DskipTests

      - name: Run tests
        run: mvn test
